name: ecomm-tutorial

on:
    push:
        branches:
            - main

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            server_changes: ${{steps.server_changed.outputs.server}}

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            
            - name: check changes for server
              id: server_changed
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                    server:
                        - './**'
    server:
        needs: check-changes
        if: needs.check-changes.outputs.server_changes=='true'
        runs-on: ubuntu-latest

        steps:
            - name: nice working you're good to go
              run: echo "Server is up and running!"
            
            - name: creating a docker image
              run: |
                docker build -t itsmonday231/api_image .
            
            - name: docker login
              env:
                DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASS: ${{secrets.DOCKER_PAT}}
              run: |
                echo $DOCKER_USER | docker login -u $DOCKER_USER --password-stdin
                docker push itsmonday231/api_image
                docker logout
    
    notify:
        needs: [server]
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: send notification
              uses: 8398a7/action-slack@v3
              with:
                 status: ${{job.status}}
                 fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
              env:
                 SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URI}}